### ISSUE TITLE
_find_library_header strange include_path

### ISSUE THREAD

**Issue by ghost** [brianbruggeman/glfw-cffi#1]
I tried to run glfw-cffi. Installed it, I have Ubuntu 16.04 with libglfw3-dev installed.
Trying to run glfw-cffi examples give endless loop, because in _find_library_header
include_path is /
Changed it to /usr/include and everything works fine.
I think it's not that efficient to walk ALL dirs

**Comment by brianbruggeman** [comment]
Hey - sorry for the late reply.  Thanks for the feedback!  

The `_find_library_header` is definitely a hack, and I am totally open to exploring a more precise way of finding the library.  As a note, I develop on a mac, so I'm positive that I won't catch everything.  I definitely want to make this cross-platform and as friendly out of the box as I can.

One thought I had here was to use some of the more standard GCC environment variables (e.g. C_INCLUDE_PATH, CPLUS_INCLUDE_PATH, LIBRARY_PATH, etc.) to help determine where to look.  Another thought might be to have an explicit glfw-cffi set of environment variables for control.  

The default fall back might always be to do a search, but given it's difficult to know where your platform may have installed things, I'm not sure how to handle this search correctly without starting at the top of the folder tree.  Perhaps a subset would be far better.  But for example, I know that in some cases, people are now using $HOME/.local or $HOME/usr/local, etc. for installation of header files.

Can you give me more insight as to why you ended up with an endless loop?  Do any of the solutions above seem like they might solve your problem in a more elegant way?
